### ISSUE TITLE
Routes missing from Miner - Oceanic - Biomass

### ISSUE THREAD

**Issue by scotrod** [DalShooth/EVE_PI_Templates#2]
Hey, and thanks for the project.

The output routes from Miner - Oceanic - Biomass Extractor Control Units are not redirecting to the Storage Facility.

**Comment by DalShooth** [comment]
Thanks for the report. Will get it resolved ASAP.

**Comment by DalShooth** [comment]
After review. This is a limitation of the way CCP designed the templates and how they are applied in game. While the json does indeed have the configurations present for the extractor routes, when the template is applied, the extractors are set back to default. When using the mining templates you have to do the follow.

1. Setup extractor heads
2. Route the outputs to the storage.

Everything else should work without user intervention.

https://github.com/DalShooth/EVE_PI_Templates?tab=readme-ov-file#faqtroubleshooting
Ive added this detail to the FAQ

**Comment by scotrod** [comment]
Again, thank you so much for your work on this project! I hope CCP "fix" this on the full release. Merry X-mas!
